[tool.cibuildwheel]
skip = ["cp36-*","cp37-*",'pp*']


#[tool.cibuildwheel.linux]
#archs = ["auto64"]
#
#[tool.cibuildwheel.macos]
#archs = ["auto64"]
#
#[tool.cibuildwheel.windows]
#archs = ["auto64"]


[project]
requires-python = ">=3.8"